/**
 * Shared types for action queue components.
 * These types are used across mobile, web, and UI packages.
 */

/**
 * Risk flag detected in a draft response.
 * Indicates potential issues that may require user review.
 */
export interface DraftRiskFlag {
  /** The category of risk (e.g., "commitment", "legal", "financial") */
  type: string;
  /** The phrase that triggered the flag */
  trigger: string;
}

/**
 * Labels for draft response tones.
 * - direct: concise, straightforward
 * - diplomatic: warmer, more considerate
 * - boundary: decline or pushback
 */
export type DraftLabel = "direct" | "diplomatic" | "boundary";

/**
 * A draft response option with metadata.
 * Generated by AI for user review and selection.
 */
export interface DraftOption {
  /** The draft response text */
  text: string;
  /** Tone label for the draft */
  label: DraftLabel;
  /** Confidence score from 0-1 */
  confidence: number;
  /** Assumptions made when generating this draft */
  assumptions: string[];
  /** Sources used for style matching */
  styleSources: string[];
  /** Risk flags detected in this draft */
  riskFlags: DraftRiskFlag[];
}

/**
 * Attachment metadata for a message.
 */
export interface MessageAttachment {
  /** Original filename, if available */
  filename: string | null;
  /** MIME type of the attachment */
  mimeType: string | null;
  /** URL to access the attachment */
  url: string | null;
  /** URL to a thumbnail preview, if available */
  thumbnailUrl?: string | null;
}

/**
 * Message data for display in the action queue.
 * Represents a single message in a conversation thread.
 */
export interface DisplayMessage {
  /** Unique message identifier */
  _id: string;
  /** Message content text */
  content: string | null;
  /** Timestamp when the message was sent (Unix ms) */
  sentAt: number;
  /** Whether this message was sent by the current user */
  isFromMe: boolean;
  /** Display name of the sender */
  senderName: string | null;
  /** Delivery status (sent, delivered, read, etc.) */
  status?: string | null;
  /** Reaction emojis on this message */
  reactions?: string[] | null;
  /** File attachments */
  attachments?: MessageAttachment[] | null;
}

/**
 * Form data for contact action cards.
 * Used when creating or updating contact information.
 */
export interface ContactFormData {
  /** Contact's full name */
  name: string;
  /** Company or organization */
  company: string;
  /** Comma-separated tags */
  tags: string;
  /** Free-form notes */
  notes: string;
  /** ID of an existing contact to link/merge with */
  linkedContactId?: string | null;
}
