export * from "./components/ui"
export * from "./components/unified-inbox"
export * from "./components/assistant"
export * from "./components/action-queue"
export * from "./components/contacts"

// ai-elements - shadcn registry components for AI chat interfaces
export {
  Conversation,
  ConversationContent,
  ConversationEmptyState,
  ConversationScrollButton,
  type ConversationProps,
  type ConversationContentProps,
  type ConversationEmptyStateProps,
  type ConversationScrollButtonProps,
} from "./components/ai-elements/conversation"

export {
  Message,
  MessageContent,
  MessageActions,
  MessageAction,
  MessageBranch,
  MessageBranchContent,
  MessageBranchSelector,
  MessageBranchPrevious,
  MessageBranchNext,
  MessageBranchPage,
  MessageResponse,
  MessageAttachment,
  MessageAttachments,
  MessageToolbar,
  type MessageProps,
  type MessageContentProps,
  type MessageActionsProps,
  type MessageActionProps,
  type MessageBranchProps,
  type MessageBranchContentProps,
  type MessageBranchSelectorProps,
  type MessageBranchPreviousProps,
  type MessageBranchNextProps,
  type MessageBranchPageProps,
  type MessageResponseProps,
  type MessageAttachmentProps,
  type MessageAttachmentsProps,
  type MessageToolbarProps,
} from "./components/ai-elements/message"

export {
  PromptInput,
  PromptInputProvider,
  PromptInputTextarea,
  PromptInputHeader,
  PromptInputFooter,
  PromptInputTools,
  PromptInputButton,
  PromptInputActionMenu,
  PromptInputActionMenuTrigger,
  PromptInputActionMenuContent,
  PromptInputActionMenuItem,
  PromptInputActionAddAttachments,
  PromptInputSubmit,
  PromptInputAttachment,
  PromptInputAttachments,
  PromptInputBody,
  PromptInputSelect,
  PromptInputSelectTrigger,
  PromptInputSelectContent,
  PromptInputSelectItem,
  PromptInputSelectValue,
  PromptInputHoverCard,
  PromptInputHoverCardTrigger,
  PromptInputHoverCardContent,
  PromptInputTabsList,
  PromptInputTab,
  PromptInputTabLabel,
  PromptInputTabBody,
  PromptInputTabItem,
  PromptInputCommand,
  PromptInputCommandInput,
  PromptInputCommandList,
  PromptInputCommandEmpty,
  PromptInputCommandGroup,
  PromptInputCommandItem,
  PromptInputCommandSeparator,
  usePromptInputController,
  useProviderAttachments,
  usePromptInputAttachments,
  type AttachmentsContext,
  type TextInputContext,
  type PromptInputControllerProps,
  type PromptInputProviderProps,
  type PromptInputProps,
  type PromptInputTextareaProps,
  type PromptInputHeaderProps,
  type PromptInputFooterProps,
  type PromptInputToolsProps,
  type PromptInputButtonProps,
  type PromptInputActionMenuProps,
  type PromptInputActionMenuTriggerProps,
  type PromptInputActionMenuContentProps,
  type PromptInputActionMenuItemProps,
  type PromptInputActionAddAttachmentsProps,
  type PromptInputSubmitProps,
  type PromptInputAttachmentProps,
  type PromptInputAttachmentsProps,
  type PromptInputBodyProps,
  type PromptInputSelectProps,
  type PromptInputSelectTriggerProps,
  type PromptInputSelectContentProps,
  type PromptInputSelectItemProps,
  type PromptInputSelectValueProps,
  type PromptInputHoverCardProps,
  type PromptInputHoverCardTriggerProps,
  type PromptInputHoverCardContentProps,
  type PromptInputTabsListProps,
  type PromptInputTabProps,
  type PromptInputTabLabelProps,
  type PromptInputTabBodyProps,
  type PromptInputTabItemProps,
  type PromptInputCommandProps,
  type PromptInputCommandInputProps,
  type PromptInputCommandListProps,
  type PromptInputCommandEmptyProps,
  type PromptInputCommandGroupProps,
  type PromptInputCommandItemProps,
  type PromptInputCommandSeparatorProps,
  type PromptInputMessage,
} from "./components/ai-elements/prompt-input"

export { Loader, type LoaderProps } from "./components/ai-elements/loader"

export {
  Reasoning,
  ReasoningTrigger,
  ReasoningContent,
  useReasoning,
  type ReasoningProps,
  type ReasoningTriggerProps,
  type ReasoningContentProps,
} from "./components/ai-elements/reasoning"

export { Shimmer, type TextShimmerProps as ShimmerProps } from "./components/ai-elements/shimmer"

export {
  Sources,
  SourcesTrigger,
  SourcesContent,
  Source,
  type SourcesProps,
  type SourcesTriggerProps,
  type SourcesContentProps,
  type SourceProps,
} from "./components/ai-elements/sources"

export {
  Suggestions,
  Suggestion,
  type SuggestionsProps,
  type SuggestionProps,
} from "./components/ai-elements/suggestion"

export { AppSidebar } from "./components/app-sidebar"
export { cn } from "./lib/utils"
