// ---------------------------
// This file was generated by Nango (v0.69.22)
// You can version this file
// ---------------------------

export interface SyncMetadata_google_emails {
  backfillPeriodMs?: number | undefined;
};

export interface GmailEmail {
  id: string;
  sender: string;
  recipients?: string | undefined;
  date: string;
  subject: string;
  body?: string | undefined;
  attachments: ({  filename: string;
  mimeType: string;
  size: number;
  attachmentId: string;})[];
  threadId: string;
  labelIds?: string[] | undefined;
};

export interface SyncMetadata_google_contacts {
  syncToken?: string | undefined;
};

export interface GoogleContact {
  id: string;
  name: string;
  emails: string[];
  phones: string[];
  company?: string | undefined;
  title?: string | undefined;
  isDeleted: boolean;
};

export interface ActionInput_google_sendemail {
  to: string;
  subject: string;
  body: string;
  threadId?: string | undefined;
  inReplyTo?: string | undefined;
  references?: string | undefined;
};

export interface ActionOutput_google_sendemail {
  id: string;
  threadId: string;
  labelIds?: string[] | undefined;
};
