// ---------------------------
// This file was generated by Nango (v0.69.22)
// You can version this file
// ---------------------------

export interface SyncMetadata_google_mail_emails {
  backfillPeriodMs?: number | undefined;
};

export interface GmailEmail {
  id: string;
  sender: string;
  recipients?: string | undefined;
  date: string;
  subject: string;
  body?: string | undefined;
  attachments: ({  filename: string;
  mimeType: string;
  size: number;
  attachmentId: string;})[];
  threadId: string;
};
